### ISSUE TITLE
name 'asset_set' is not defined

### ISSUE THREAD

**Issue by zdong08** [philmatu/snipe-it-api-adapter#1]
hello,python api.py  error
python api.py 
http://snipe-test.com
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    asset_id = snipe.getAssetId(tag=asset_set['category']+"/"+asset_set['serial'])
NameError: name 'asset_set' is not defined

api.py file
cat api.py 
from SnipeAPIAdapter import SnipeAPIAdapter
import json
import datetime
from dateutil import parser
import pytz
import urllib
snipe = SnipeAPIAdapter('http://snipe-test.com','test','123456')

asset_id = snipe.getAssetId(tag=asset_set['category']+"/"+asset_set['serial'])
if asset_id is not False:
    #does the asset have accurate information?
        data_asset_edit = snipe.getAssetData(id=asset_id)
        data_asset_username = snipe.getAssetUsername(tag=asset_set['category']+"/"+asset_set['serial'])

else:
        #add a new asset based on our information
        #defaults
        monitorable_custom_fields = ["Monitoring"]
        fieldset_id = snipe.getCustomFieldSets(name="Monitorable", custom_fields=monitorable_custom_fields)
        status_ids = snipe.getStatusId()
        deployable_status_id = status_ids['Ready to Deploy']
        #specifics
        company_id = snipe.getCompanyId(company)
        model_id = snipe.getAssetModelId(asset_model_name=asset_set['model'], manufacturer=asset_set['manufacturer'], category=asset_set['category'], custom_fieldset_id=fieldset_id)
        user_id = snipe.getUserId(username=str(asset_set['vehicle_id']), group=depot)
        asset_id = snipe.getAssetId(tag=asset_set['category']+"/"+asset_set['serial'], serial=asset_set['serial'], model_id=model_id, company_id=company_id, status_id=deployable_status_id)
        snipe.checkout(asset_id=asset_id, user_id=user_id)

sipe.cleanup()

**Comment by philmatu** [comment]
I've fixed the readme by defining the asset_set array, which it is complaining about.

Try using this definition for the asset_set associative array: 
asset_set = {"category":"computer", "serial":"123456", "model":"inspiron", "manufacturer":"dell", "username":"sampleuser"}

**Comment by zdong08** [comment]
thankyou！
